openapi: 3.0.0
info:
  title: Gemini Proxy API
  version: "1.0.0"
  description: Uma API que atua como um proxy inteligente para a API do Gemini, com cache e segurança.
servers:
  - url: http://localhost:3000
    description: Servidor de Desenvolvimento

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: "Mensagem de erro descritiva."
    SuccessResponse:
      type: object
      properties:
        response:
          type: string
          example: "A resposta gerada pela IA do Gemini."
        fromCache:
          type: boolean
          example: false

tags:
  - name: Gemini
    description: Endpoints para interação com a API do Gemini

security:
  - apiKeyAuth: []

paths:
  /api/v1/ask:
    post:
      tags:
        - Gemini
      summary: Envia um prompt para a API do Gemini
      description: Recebe um prompt, o envia para a API do Gemini (utilizando cache) e retorna a resposta.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - prompt
              properties:
                prompt:
                  type: string
                  description: O texto da pergunta a ser enviada para o Gemini.
                  example: "Qual a distância da Terra até a Lua?"
      responses:
        